-- telegram-tt Supabase schema (Telegram-like MVP)
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  phone_number text unique,
  username text unique,
  first_name text not null default '',
  last_name text not null default '',
  display_name text not null default '',
  bio text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dialogs (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('private', 'group', 'channel')),
  title text,
  created_by_profile_id uuid references public.profiles(id) on delete set null,
  avatar_url text,
  last_message_id bigint,
  last_message_preview text,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dialog_members (
  id uuid primary key default gen_random_uuid(),
  dialog_id uuid not null references public.dialogs(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member',
  joined_at timestamptz not null default now(),
  unique (dialog_id, profile_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  dialog_id uuid not null references public.dialogs(id) on delete cascade,
  sender_profile_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  message_type text not null default 'text',
  reply_to_message_id bigint references public.messages(id) on delete set null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gifts (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  description text,
  icon_url text,
  price_stars integer not null default 0,
  rarity text,
  is_active boolean not null default true,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_gifts (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  gift_id uuid not null references public.gifts(id) on delete cascade,
  acquired_at timestamptz not null default now(),
  source_type text,
  message text,
  is_displayed_on_profile boolean not null default true,
  metadata_json jsonb not null default '{}'::jsonb
);

create table if not exists public.stars_balances (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique not null references public.profiles(id) on delete cascade,
  balance integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.stars_transactions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  transaction_type text not null,
  reference_type text,
  reference_id text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.dialogs enable row level security;
alter table public.dialog_members enable row level security;
alter table public.messages enable row level security;
alter table public.gifts enable row level security;
alter table public.profile_gifts enable row level security;
alter table public.stars_balances enable row level security;
alter table public.stars_transactions enable row level security;

create policy "profiles_select_own_or_public" on public.profiles for select using (true);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = auth_user_id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = auth_user_id or auth_user_id is null);

create policy "dialogs_select_members" on public.dialogs for select using (
  exists (
    select 1 from public.dialog_members dm
    join public.profiles p on p.id = dm.profile_id
    where dm.dialog_id = dialogs.id and p.auth_user_id = auth.uid()
  )
);

create policy "dialog_members_select_own" on public.dialog_members for select using (
  exists (
    select 1 from public.profiles p
    where p.id = dialog_members.profile_id and p.auth_user_id = auth.uid()
  )
);

create policy "messages_select_members" on public.messages for select using (
  exists (
    select 1 from public.dialog_members dm
    join public.profiles p on p.id = dm.profile_id
    where dm.dialog_id = messages.dialog_id and p.auth_user_id = auth.uid()
  )
);

create policy "messages_insert_members" on public.messages for insert with check (
  exists (
    select 1 from public.profiles p
    where p.id = sender_profile_id and p.auth_user_id = auth.uid()
  )
  and exists (
    select 1 from public.dialog_members dm
    where dm.dialog_id = messages.dialog_id and dm.profile_id = sender_profile_id
  )
);

create policy "gifts_select_active" on public.gifts for select using (is_active = true);

create policy "profile_gifts_select_owner" on public.profile_gifts for select using (
  exists (
    select 1 from public.profiles p
    where p.id = profile_gifts.profile_id and p.auth_user_id = auth.uid()
  )
);

create policy "stars_balances_select_owner" on public.stars_balances for select using (
  exists (
    select 1 from public.profiles p
    where p.id = stars_balances.profile_id and p.auth_user_id = auth.uid()
  )
);

create policy "stars_transactions_select_owner" on public.stars_transactions for select using (
  exists (
    select 1 from public.profiles p
    where p.id = stars_transactions.profile_id and p.auth_user_id = auth.uid()
  )
);
